### PR TITLE
New header and footer

### PR DESCRIPTION
**Pull request by tillywoodfield**

### CODE REVIEW

**Comment by tillywoodfield** [comment]
@robredpath, here is an initial version of the new header/footer on the Sphinx theme to look at and let me know which sections/links should be included etc.

**Comment by robredpath** [comment]
I've deployed this to https://iati-sphinx-theme.readthedocs-hosted.com/en/design-system-upgrade/ for testing and demo

**Comment by robredpath** [comment]
Exciting! 

**Header**
* Remove the Help Docs link because these are the help docs
* Keep the English (even if there's only English) because it tells the user that it's only available in English. 
* Make "Tool Home" take on the name of the tool (ideally from conf). 

**Footer**
I think we can condense that down to two horizontal sections: a top one (called "additional information") with the Sphinx version, a link to the GH repo where the docs come from and the license (CC-BY-4.0 with link); a bottom one as-is without the Sphinx version

**Comment by robredpath** [comment]
Oh - and one other question. What do we want to do about the floating RTD switcher widget? We probably want it for version switching during development but I don't think we want to include it in our users' interactions. 

Can we do something smart like make it appear if we have a certain cookie set or something like that?

**Comment by tillywoodfield** [comment]
@robredpath I've updated the header and footer as per your comments, and as discussed we will leave the RTD flyout menu as-is for now and look into how we can choose display or hide it at build time as a follow up task

**Review by robredpath — APPROVED** [review]
🎉

**Pull request merged**
